server:
  port: 8888
spring:
  application:
    name: gateway-learn
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      # 是否开启网关，默认是true - 开启
      enabled: true
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          # http://localhost:8888/mall-order/order/findOrderByUserId/1
          enabled: false
      # 跨域
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTION
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**


