server:
  port: 8300
spring:
  application:
    name: ribbon-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: SH
#        metadata:
#          version: v2

# 被调用的微服务名 -> 当需要使用局部配置的时候推荐使用这种方式
#mall-order:
#  ribbon:
#    #指定使用Nacos提供的负载均衡策略（优先调用同一集群的实例，基于随机&权重）
#    #NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#    # 自定义的负载均衡策略（基于随机&权重）
#    NFLoadBalancerRuleClassName: com.example.ribbon.rule.NacosRandomWithWeights

ribbon:
  eager-load:
    # 开启饥饿加载，默认是懒加载（第一次调用的时候会去初始化有点慢），启动的时候初始化
    enabled: true
    # 配置mall-user使用ribbon饥饿加载，多个使用逗号分隔
    clients: mall-order

management:
  endpoints:
    web:
      exposure:
        include: '*'



