server:
  port: 8300
spring:
  application:
    name: ribbon-demo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.65.228:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
