server:
  port: 8085

spring:
  application:
    name: provider-demo

  cloud:
    # 配置nacos
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
