spring:
  redis:
    host: 123.60.150.23
    port: 6379
    password: root@123456

server:
  port: 8083
  #防止Cookie冲突，冲突会导致登录验证不通过
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID${server.port}
      # 设置了 Session 的过期时间，单位为秒，这里设置为 6 小时，这里我为了测试session 未过期但是 token 过期后客户端系统能否正常访问
      # 测试发现 session 未过期但是 token 显示已过期，客户端系统能正常访问
      # 说明该跨域单点登录登录成功后不校验 token，只要 session 未过期就能正常访问
      timeout: 21600

#与授权服务器对应的配置
security:
  oauth2:
    client:
      client-id: client
      client-secret: 123123
      user-authorization-uri: http://localhost:8081/oauth/authorize
      access-token-uri:  http://localhost:8081/oauth/token
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token

