version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-server
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=172.17.0.1
      - MYSQL_SERVICE_PORT=33056
      - MYSQL_SERVICE_DB_NAME=test-nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=password

    volumes:
      - ./logs/:/home/nacos/logs
    ports:
      - "8848:8848"