spring:
  redis:
    host: 123.60.150.23
    port: 6379
    password: root@123456

# 也可以直接在 com.example.demo.config.AuthorizationServerConfig.configure(ClientDetailsServiceConfigurer)
# 进行配置
#security:
#  oauth2:
#    client:
#      # 修改token有效期
#      access-token-validity-seconds: 3600
